Declare go 1.15 in go.mod
This is a soft requirement: older versions of Go shows a message
*if* the build fails.
In this case with Go 1.14 the build does fail, so this helps:

 cd examples && \
 for i in *.go; do \
 	go build ${i} || exit 1; \
 done
 # github.com/openshift-online/ocm-sdk-go
 ../send.go:340:14: undefined: tls.Dialer
 ../send.go:343:4: not enough arguments to return
+note: module requires Go 1.15
 make: *** [Makefile:34: examples] Error 1